/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups.index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps.index'
import { Route as AuthenticatedAppBuilderIndexRouteImport } from './routes/_authenticated/app-builder.index'
import { Route as AuthenticatedUsersGroupsRouteImport } from './routes/_authenticated/users/groups'
import { Route as AuthenticatedUsersCreateRouteImport } from './routes/_authenticated/users.create'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated/users.$id'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings.account'
import { Route as AuthenticatedGroupsCreateRouteImport } from './routes/_authenticated/groups/create'
import { Route as AuthenticatedGroupsIdRouteImport } from './routes/_authenticated/groups.$id'
import { Route as AuthenticatedAppsIdRouteImport } from './routes/_authenticated/apps.$id'
import { Route as AuthenticatedAppBuilderSystemStatusRouteImport } from './routes/_authenticated/app-builder.system-status'
import { Route as AuthenticatedAppBuilderSettingsRouteImport } from './routes/_authenticated/app-builder/settings'
import { Route as AuthenticatedAppBuilderIdentifierRouteImport } from './routes/_authenticated/app-builder.identifier'
import { Route as AuthenticatedAppBuilderCreateRouteImport } from './routes/_authenticated/app-builder.create'
import { Route as AuthenticatedAppsIdIndexRouteImport } from './routes/_authenticated/apps.$id.index'
import { Route as AuthenticatedUsersIdViewRouteImport } from './routes/_authenticated/users.$id.view'
import { Route as AuthenticatedUsersIdEditRouteImport } from './routes/_authenticated/users.$id.edit'
import { Route as AuthenticatedAppsIdLoginsRouteImport } from './routes/_authenticated/apps.$id.logins'
import { Route as AuthenticatedAppBuilderIdHistoryRouteImport } from './routes/_authenticated/app-builder.$id.history'
import { Route as AuthenticatedAppBuilderIdBuildRouteImport } from './routes/_authenticated/app-builder.$id.build'
import { Route as AuthenticatedAppBuilderIdHistoryBuildIdRouteImport } from './routes/_authenticated/app-builder.$id.history.$buildId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppsRoute,
} as any)
const AuthenticatedAppBuilderIndexRoute =
  AuthenticatedAppBuilderIndexRouteImport.update({
    id: '/app-builder/',
    path: '/app-builder/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersGroupsRoute =
  AuthenticatedUsersGroupsRouteImport.update({
    id: '/groups',
    path: '/groups',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedUsersCreateRoute =
  AuthenticatedUsersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedGroupsCreateRoute =
  AuthenticatedGroupsCreateRouteImport.update({
    id: '/groups/create',
    path: '/groups/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsIdRoute = AuthenticatedGroupsIdRouteImport.update({
  id: '/groups/$id',
  path: '/groups/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsIdRoute = AuthenticatedAppsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAppsRoute,
} as any)
const AuthenticatedAppBuilderSystemStatusRoute =
  AuthenticatedAppBuilderSystemStatusRouteImport.update({
    id: '/app-builder/system-status',
    path: '/app-builder/system-status',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppBuilderSettingsRoute =
  AuthenticatedAppBuilderSettingsRouteImport.update({
    id: '/app-builder/settings',
    path: '/app-builder/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppBuilderIdentifierRoute =
  AuthenticatedAppBuilderIdentifierRouteImport.update({
    id: '/app-builder/identifier',
    path: '/app-builder/identifier',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppBuilderCreateRoute =
  AuthenticatedAppBuilderCreateRouteImport.update({
    id: '/app-builder/create',
    path: '/app-builder/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppsIdIndexRoute =
  AuthenticatedAppsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppsIdRoute,
  } as any)
const AuthenticatedUsersIdViewRoute =
  AuthenticatedUsersIdViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => AuthenticatedUsersIdRoute,
  } as any)
const AuthenticatedUsersIdEditRoute =
  AuthenticatedUsersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedUsersIdRoute,
  } as any)
const AuthenticatedAppsIdLoginsRoute =
  AuthenticatedAppsIdLoginsRouteImport.update({
    id: '/logins',
    path: '/logins',
    getParentRoute: () => AuthenticatedAppsIdRoute,
  } as any)
const AuthenticatedAppBuilderIdHistoryRoute =
  AuthenticatedAppBuilderIdHistoryRouteImport.update({
    id: '/app-builder/$id/history',
    path: '/app-builder/$id/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppBuilderIdBuildRoute =
  AuthenticatedAppBuilderIdBuildRouteImport.update({
    id: '/app-builder/$id/build',
    path: '/app-builder/$id/build',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAppBuilderIdHistoryBuildIdRoute =
  AuthenticatedAppBuilderIdHistoryBuildIdRouteImport.update({
    id: '/$buildId',
    path: '/$buildId',
    getParentRoute: () => AuthenticatedAppBuilderIdHistoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/apps': typeof AuthenticatedAppsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/app-builder/create': typeof AuthenticatedAppBuilderCreateRoute
  '/app-builder/identifier': typeof AuthenticatedAppBuilderIdentifierRoute
  '/app-builder/settings': typeof AuthenticatedAppBuilderSettingsRoute
  '/app-builder/system-status': typeof AuthenticatedAppBuilderSystemStatusRoute
  '/apps/$id': typeof AuthenticatedAppsIdRouteWithChildren
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/groups/create': typeof AuthenticatedGroupsCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/users/$id': typeof AuthenticatedUsersIdRouteWithChildren
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/users/groups': typeof AuthenticatedUsersGroupsRoute
  '/app-builder': typeof AuthenticatedAppBuilderIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/app-builder/$id/build': typeof AuthenticatedAppBuilderIdBuildRoute
  '/app-builder/$id/history': typeof AuthenticatedAppBuilderIdHistoryRouteWithChildren
  '/apps/$id/logins': typeof AuthenticatedAppsIdLoginsRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/users/$id/view': typeof AuthenticatedUsersIdViewRoute
  '/apps/$id/': typeof AuthenticatedAppsIdIndexRoute
  '/app-builder/$id/history/$buildId': typeof AuthenticatedAppBuilderIdHistoryBuildIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/app-builder/create': typeof AuthenticatedAppBuilderCreateRoute
  '/app-builder/identifier': typeof AuthenticatedAppBuilderIdentifierRoute
  '/app-builder/settings': typeof AuthenticatedAppBuilderSettingsRoute
  '/app-builder/system-status': typeof AuthenticatedAppBuilderSystemStatusRoute
  '/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/groups/create': typeof AuthenticatedGroupsCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/users/$id': typeof AuthenticatedUsersIdRouteWithChildren
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/users/groups': typeof AuthenticatedUsersGroupsRoute
  '/app-builder': typeof AuthenticatedAppBuilderIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/app-builder/$id/build': typeof AuthenticatedAppBuilderIdBuildRoute
  '/app-builder/$id/history': typeof AuthenticatedAppBuilderIdHistoryRouteWithChildren
  '/apps/$id/logins': typeof AuthenticatedAppsIdLoginsRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/users/$id/view': typeof AuthenticatedUsersIdViewRoute
  '/apps/$id': typeof AuthenticatedAppsIdIndexRoute
  '/app-builder/$id/history/$buildId': typeof AuthenticatedAppBuilderIdHistoryBuildIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/app-builder/create': typeof AuthenticatedAppBuilderCreateRoute
  '/_authenticated/app-builder/identifier': typeof AuthenticatedAppBuilderIdentifierRoute
  '/_authenticated/app-builder/settings': typeof AuthenticatedAppBuilderSettingsRoute
  '/_authenticated/app-builder/system-status': typeof AuthenticatedAppBuilderSystemStatusRoute
  '/_authenticated/apps/$id': typeof AuthenticatedAppsIdRouteWithChildren
  '/_authenticated/groups/$id': typeof AuthenticatedGroupsIdRoute
  '/_authenticated/groups/create': typeof AuthenticatedGroupsCreateRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRouteWithChildren
  '/_authenticated/users/create': typeof AuthenticatedUsersCreateRoute
  '/_authenticated/users/groups': typeof AuthenticatedUsersGroupsRoute
  '/_authenticated/app-builder/': typeof AuthenticatedAppBuilderIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/app-builder/$id/build': typeof AuthenticatedAppBuilderIdBuildRoute
  '/_authenticated/app-builder/$id/history': typeof AuthenticatedAppBuilderIdHistoryRouteWithChildren
  '/_authenticated/apps/$id/logins': typeof AuthenticatedAppsIdLoginsRoute
  '/_authenticated/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/_authenticated/users/$id/view': typeof AuthenticatedUsersIdViewRoute
  '/_authenticated/apps/$id/': typeof AuthenticatedAppsIdIndexRoute
  '/_authenticated/app-builder/$id/history/$buildId': typeof AuthenticatedAppBuilderIdHistoryBuildIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/apps'
    | '/dashboard'
    | '/settings'
    | '/users'
    | '/app-builder/create'
    | '/app-builder/identifier'
    | '/app-builder/settings'
    | '/app-builder/system-status'
    | '/apps/$id'
    | '/groups/$id'
    | '/groups/create'
    | '/settings/account'
    | '/settings/profile'
    | '/users/$id'
    | '/users/create'
    | '/users/groups'
    | '/app-builder'
    | '/apps/'
    | '/groups'
    | '/users/'
    | '/app-builder/$id/build'
    | '/app-builder/$id/history'
    | '/apps/$id/logins'
    | '/users/$id/edit'
    | '/users/$id/view'
    | '/apps/$id/'
    | '/app-builder/$id/history/$buildId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/dashboard'
    | '/settings'
    | '/app-builder/create'
    | '/app-builder/identifier'
    | '/app-builder/settings'
    | '/app-builder/system-status'
    | '/groups/$id'
    | '/groups/create'
    | '/settings/account'
    | '/settings/profile'
    | '/users/$id'
    | '/users/create'
    | '/users/groups'
    | '/app-builder'
    | '/apps'
    | '/groups'
    | '/users'
    | '/app-builder/$id/build'
    | '/app-builder/$id/history'
    | '/apps/$id/logins'
    | '/users/$id/edit'
    | '/users/$id/view'
    | '/apps/$id'
    | '/app-builder/$id/history/$buildId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/apps'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/app-builder/create'
    | '/_authenticated/app-builder/identifier'
    | '/_authenticated/app-builder/settings'
    | '/_authenticated/app-builder/system-status'
    | '/_authenticated/apps/$id'
    | '/_authenticated/groups/$id'
    | '/_authenticated/groups/create'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/profile'
    | '/_authenticated/users/$id'
    | '/_authenticated/users/create'
    | '/_authenticated/users/groups'
    | '/_authenticated/app-builder/'
    | '/_authenticated/apps/'
    | '/_authenticated/groups/'
    | '/_authenticated/users/'
    | '/_authenticated/app-builder/$id/build'
    | '/_authenticated/app-builder/$id/history'
    | '/_authenticated/apps/$id/logins'
    | '/_authenticated/users/$id/edit'
    | '/_authenticated/users/$id/view'
    | '/_authenticated/apps/$id/'
    | '/_authenticated/app-builder/$id/history/$buildId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedAppsRoute
    }
    '/_authenticated/app-builder/': {
      id: '/_authenticated/app-builder/'
      path: '/app-builder'
      fullPath: '/app-builder'
      preLoaderRoute: typeof AuthenticatedAppBuilderIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/groups': {
      id: '/_authenticated/users/groups'
      path: '/groups'
      fullPath: '/users/groups'
      preLoaderRoute: typeof AuthenticatedUsersGroupsRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/users/create': {
      id: '/_authenticated/users/create'
      path: '/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthenticatedUsersCreateRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/groups/create': {
      id: '/_authenticated/groups/create'
      path: '/groups/create'
      fullPath: '/groups/create'
      preLoaderRoute: typeof AuthenticatedGroupsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/$id': {
      id: '/_authenticated/groups/$id'
      path: '/groups/$id'
      fullPath: '/groups/$id'
      preLoaderRoute: typeof AuthenticatedGroupsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/$id': {
      id: '/_authenticated/apps/$id'
      path: '/$id'
      fullPath: '/apps/$id'
      preLoaderRoute: typeof AuthenticatedAppsIdRouteImport
      parentRoute: typeof AuthenticatedAppsRoute
    }
    '/_authenticated/app-builder/system-status': {
      id: '/_authenticated/app-builder/system-status'
      path: '/app-builder/system-status'
      fullPath: '/app-builder/system-status'
      preLoaderRoute: typeof AuthenticatedAppBuilderSystemStatusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-builder/settings': {
      id: '/_authenticated/app-builder/settings'
      path: '/app-builder/settings'
      fullPath: '/app-builder/settings'
      preLoaderRoute: typeof AuthenticatedAppBuilderSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-builder/identifier': {
      id: '/_authenticated/app-builder/identifier'
      path: '/app-builder/identifier'
      fullPath: '/app-builder/identifier'
      preLoaderRoute: typeof AuthenticatedAppBuilderIdentifierRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-builder/create': {
      id: '/_authenticated/app-builder/create'
      path: '/app-builder/create'
      fullPath: '/app-builder/create'
      preLoaderRoute: typeof AuthenticatedAppBuilderCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps/$id/': {
      id: '/_authenticated/apps/$id/'
      path: '/'
      fullPath: '/apps/$id/'
      preLoaderRoute: typeof AuthenticatedAppsIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppsIdRoute
    }
    '/_authenticated/users/$id/view': {
      id: '/_authenticated/users/$id/view'
      path: '/view'
      fullPath: '/users/$id/view'
      preLoaderRoute: typeof AuthenticatedUsersIdViewRouteImport
      parentRoute: typeof AuthenticatedUsersIdRoute
    }
    '/_authenticated/users/$id/edit': {
      id: '/_authenticated/users/$id/edit'
      path: '/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof AuthenticatedUsersIdEditRouteImport
      parentRoute: typeof AuthenticatedUsersIdRoute
    }
    '/_authenticated/apps/$id/logins': {
      id: '/_authenticated/apps/$id/logins'
      path: '/logins'
      fullPath: '/apps/$id/logins'
      preLoaderRoute: typeof AuthenticatedAppsIdLoginsRouteImport
      parentRoute: typeof AuthenticatedAppsIdRoute
    }
    '/_authenticated/app-builder/$id/history': {
      id: '/_authenticated/app-builder/$id/history'
      path: '/app-builder/$id/history'
      fullPath: '/app-builder/$id/history'
      preLoaderRoute: typeof AuthenticatedAppBuilderIdHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-builder/$id/build': {
      id: '/_authenticated/app-builder/$id/build'
      path: '/app-builder/$id/build'
      fullPath: '/app-builder/$id/build'
      preLoaderRoute: typeof AuthenticatedAppBuilderIdBuildRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app-builder/$id/history/$buildId': {
      id: '/_authenticated/app-builder/$id/history/$buildId'
      path: '/$buildId'
      fullPath: '/app-builder/$id/history/$buildId'
      preLoaderRoute: typeof AuthenticatedAppBuilderIdHistoryBuildIdRouteImport
      parentRoute: typeof AuthenticatedAppBuilderIdHistoryRoute
    }
  }
}

interface AuthenticatedAppsIdRouteChildren {
  AuthenticatedAppsIdLoginsRoute: typeof AuthenticatedAppsIdLoginsRoute
  AuthenticatedAppsIdIndexRoute: typeof AuthenticatedAppsIdIndexRoute
}

const AuthenticatedAppsIdRouteChildren: AuthenticatedAppsIdRouteChildren = {
  AuthenticatedAppsIdLoginsRoute: AuthenticatedAppsIdLoginsRoute,
  AuthenticatedAppsIdIndexRoute: AuthenticatedAppsIdIndexRoute,
}

const AuthenticatedAppsIdRouteWithChildren =
  AuthenticatedAppsIdRoute._addFileChildren(AuthenticatedAppsIdRouteChildren)

interface AuthenticatedAppsRouteChildren {
  AuthenticatedAppsIdRoute: typeof AuthenticatedAppsIdRouteWithChildren
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
}

const AuthenticatedAppsRouteChildren: AuthenticatedAppsRouteChildren = {
  AuthenticatedAppsIdRoute: AuthenticatedAppsIdRouteWithChildren,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
}

const AuthenticatedAppsRouteWithChildren =
  AuthenticatedAppsRoute._addFileChildren(AuthenticatedAppsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedUsersIdRouteChildren {
  AuthenticatedUsersIdEditRoute: typeof AuthenticatedUsersIdEditRoute
  AuthenticatedUsersIdViewRoute: typeof AuthenticatedUsersIdViewRoute
}

const AuthenticatedUsersIdRouteChildren: AuthenticatedUsersIdRouteChildren = {
  AuthenticatedUsersIdEditRoute: AuthenticatedUsersIdEditRoute,
  AuthenticatedUsersIdViewRoute: AuthenticatedUsersIdViewRoute,
}

const AuthenticatedUsersIdRouteWithChildren =
  AuthenticatedUsersIdRoute._addFileChildren(AuthenticatedUsersIdRouteChildren)

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRouteWithChildren
  AuthenticatedUsersCreateRoute: typeof AuthenticatedUsersCreateRoute
  AuthenticatedUsersGroupsRoute: typeof AuthenticatedUsersGroupsRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRouteWithChildren,
  AuthenticatedUsersCreateRoute: AuthenticatedUsersCreateRoute,
  AuthenticatedUsersGroupsRoute: AuthenticatedUsersGroupsRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedAppBuilderIdHistoryRouteChildren {
  AuthenticatedAppBuilderIdHistoryBuildIdRoute: typeof AuthenticatedAppBuilderIdHistoryBuildIdRoute
}

const AuthenticatedAppBuilderIdHistoryRouteChildren: AuthenticatedAppBuilderIdHistoryRouteChildren =
  {
    AuthenticatedAppBuilderIdHistoryBuildIdRoute:
      AuthenticatedAppBuilderIdHistoryBuildIdRoute,
  }

const AuthenticatedAppBuilderIdHistoryRouteWithChildren =
  AuthenticatedAppBuilderIdHistoryRoute._addFileChildren(
    AuthenticatedAppBuilderIdHistoryRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
  AuthenticatedAppBuilderCreateRoute: typeof AuthenticatedAppBuilderCreateRoute
  AuthenticatedAppBuilderIdentifierRoute: typeof AuthenticatedAppBuilderIdentifierRoute
  AuthenticatedAppBuilderSettingsRoute: typeof AuthenticatedAppBuilderSettingsRoute
  AuthenticatedAppBuilderSystemStatusRoute: typeof AuthenticatedAppBuilderSystemStatusRoute
  AuthenticatedGroupsIdRoute: typeof AuthenticatedGroupsIdRoute
  AuthenticatedGroupsCreateRoute: typeof AuthenticatedGroupsCreateRoute
  AuthenticatedAppBuilderIndexRoute: typeof AuthenticatedAppBuilderIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedAppBuilderIdBuildRoute: typeof AuthenticatedAppBuilderIdBuildRoute
  AuthenticatedAppBuilderIdHistoryRoute: typeof AuthenticatedAppBuilderIdHistoryRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppsRoute: AuthenticatedAppsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
  AuthenticatedAppBuilderCreateRoute: AuthenticatedAppBuilderCreateRoute,
  AuthenticatedAppBuilderIdentifierRoute:
    AuthenticatedAppBuilderIdentifierRoute,
  AuthenticatedAppBuilderSettingsRoute: AuthenticatedAppBuilderSettingsRoute,
  AuthenticatedAppBuilderSystemStatusRoute:
    AuthenticatedAppBuilderSystemStatusRoute,
  AuthenticatedGroupsIdRoute: AuthenticatedGroupsIdRoute,
  AuthenticatedGroupsCreateRoute: AuthenticatedGroupsCreateRoute,
  AuthenticatedAppBuilderIndexRoute: AuthenticatedAppBuilderIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedAppBuilderIdBuildRoute: AuthenticatedAppBuilderIdBuildRoute,
  AuthenticatedAppBuilderIdHistoryRoute:
    AuthenticatedAppBuilderIdHistoryRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
