/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppsRouteImport } from './routes/_authenticated/apps'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users.index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps.index'
import { Route as AuthenticatedUsersCreateRouteImport } from './routes/_authenticated/users.create'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated/users.$id'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings.account'
import { Route as AuthenticatedAppsIdRouteImport } from './routes/_authenticated/apps.$id'
import { Route as AuthenticatedAppsIdIndexRouteImport } from './routes/_authenticated/apps.$id.index'
import { Route as AuthenticatedUsersIdViewRouteImport } from './routes/_authenticated/users.$id.view'
import { Route as AuthenticatedUsersIdEditRouteImport } from './routes/_authenticated/users.$id.edit'
import { Route as AuthenticatedAppsIdLoginsRouteImport } from './routes/_authenticated/apps.$id.logins'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppsRoute = AuthenticatedAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppsRoute,
} as any)
const AuthenticatedUsersCreateRoute =
  AuthenticatedUsersCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedUsersRoute,
  } as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedUsersRoute,
} as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedAppsIdRoute = AuthenticatedAppsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAppsRoute,
} as any)
const AuthenticatedAppsIdIndexRoute =
  AuthenticatedAppsIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppsIdRoute,
  } as any)
const AuthenticatedUsersIdViewRoute =
  AuthenticatedUsersIdViewRouteImport.update({
    id: '/view',
    path: '/view',
    getParentRoute: () => AuthenticatedUsersIdRoute,
  } as any)
const AuthenticatedUsersIdEditRoute =
  AuthenticatedUsersIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedUsersIdRoute,
  } as any)
const AuthenticatedAppsIdLoginsRoute =
  AuthenticatedAppsIdLoginsRouteImport.update({
    id: '/logins',
    path: '/logins',
    getParentRoute: () => AuthenticatedAppsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/apps': typeof AuthenticatedAppsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/users': typeof AuthenticatedUsersRouteWithChildren
  '/apps/$id': typeof AuthenticatedAppsIdRouteWithChildren
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/users/$id': typeof AuthenticatedUsersIdRouteWithChildren
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/apps/$id/logins': typeof AuthenticatedAppsIdLoginsRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/users/$id/view': typeof AuthenticatedUsersIdViewRoute
  '/apps/$id/': typeof AuthenticatedAppsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/users/$id': typeof AuthenticatedUsersIdRouteWithChildren
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/apps/$id/logins': typeof AuthenticatedAppsIdLoginsRoute
  '/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/users/$id/view': typeof AuthenticatedUsersIdViewRoute
  '/apps/$id': typeof AuthenticatedAppsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/apps': typeof AuthenticatedAppsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRouteWithChildren
  '/_authenticated/apps/$id': typeof AuthenticatedAppsIdRouteWithChildren
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRouteWithChildren
  '/_authenticated/users/create': typeof AuthenticatedUsersCreateRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/apps/$id/logins': typeof AuthenticatedAppsIdLoginsRoute
  '/_authenticated/users/$id/edit': typeof AuthenticatedUsersIdEditRoute
  '/_authenticated/users/$id/view': typeof AuthenticatedUsersIdViewRoute
  '/_authenticated/apps/$id/': typeof AuthenticatedAppsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/apps'
    | '/dashboard'
    | '/settings'
    | '/users'
    | '/apps/$id'
    | '/settings/account'
    | '/settings/profile'
    | '/users/$id'
    | '/users/create'
    | '/apps/'
    | '/users/'
    | '/apps/$id/logins'
    | '/users/$id/edit'
    | '/users/$id/view'
    | '/apps/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/unauthorized'
    | '/dashboard'
    | '/settings'
    | '/settings/account'
    | '/settings/profile'
    | '/users/$id'
    | '/users/create'
    | '/apps'
    | '/users'
    | '/apps/$id/logins'
    | '/users/$id/edit'
    | '/users/$id/view'
    | '/apps/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/unauthorized'
    | '/_authenticated/apps'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/apps/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/profile'
    | '/_authenticated/users/$id'
    | '/_authenticated/users/create'
    | '/_authenticated/apps/'
    | '/_authenticated/users/'
    | '/_authenticated/apps/$id/logins'
    | '/_authenticated/users/$id/edit'
    | '/_authenticated/users/$id/view'
    | '/_authenticated/apps/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/apps': {
      id: '/_authenticated/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedAppsRoute
    }
    '/_authenticated/users/create': {
      id: '/_authenticated/users/create'
      path: '/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthenticatedUsersCreateRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedUsersRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/apps/$id': {
      id: '/_authenticated/apps/$id'
      path: '/$id'
      fullPath: '/apps/$id'
      preLoaderRoute: typeof AuthenticatedAppsIdRouteImport
      parentRoute: typeof AuthenticatedAppsRoute
    }
    '/_authenticated/apps/$id/': {
      id: '/_authenticated/apps/$id/'
      path: '/'
      fullPath: '/apps/$id/'
      preLoaderRoute: typeof AuthenticatedAppsIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppsIdRoute
    }
    '/_authenticated/users/$id/view': {
      id: '/_authenticated/users/$id/view'
      path: '/view'
      fullPath: '/users/$id/view'
      preLoaderRoute: typeof AuthenticatedUsersIdViewRouteImport
      parentRoute: typeof AuthenticatedUsersIdRoute
    }
    '/_authenticated/users/$id/edit': {
      id: '/_authenticated/users/$id/edit'
      path: '/edit'
      fullPath: '/users/$id/edit'
      preLoaderRoute: typeof AuthenticatedUsersIdEditRouteImport
      parentRoute: typeof AuthenticatedUsersIdRoute
    }
    '/_authenticated/apps/$id/logins': {
      id: '/_authenticated/apps/$id/logins'
      path: '/logins'
      fullPath: '/apps/$id/logins'
      preLoaderRoute: typeof AuthenticatedAppsIdLoginsRouteImport
      parentRoute: typeof AuthenticatedAppsIdRoute
    }
  }
}

interface AuthenticatedAppsIdRouteChildren {
  AuthenticatedAppsIdLoginsRoute: typeof AuthenticatedAppsIdLoginsRoute
  AuthenticatedAppsIdIndexRoute: typeof AuthenticatedAppsIdIndexRoute
}

const AuthenticatedAppsIdRouteChildren: AuthenticatedAppsIdRouteChildren = {
  AuthenticatedAppsIdLoginsRoute: AuthenticatedAppsIdLoginsRoute,
  AuthenticatedAppsIdIndexRoute: AuthenticatedAppsIdIndexRoute,
}

const AuthenticatedAppsIdRouteWithChildren =
  AuthenticatedAppsIdRoute._addFileChildren(AuthenticatedAppsIdRouteChildren)

interface AuthenticatedAppsRouteChildren {
  AuthenticatedAppsIdRoute: typeof AuthenticatedAppsIdRouteWithChildren
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
}

const AuthenticatedAppsRouteChildren: AuthenticatedAppsRouteChildren = {
  AuthenticatedAppsIdRoute: AuthenticatedAppsIdRouteWithChildren,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
}

const AuthenticatedAppsRouteWithChildren =
  AuthenticatedAppsRoute._addFileChildren(AuthenticatedAppsRouteChildren)

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedUsersIdRouteChildren {
  AuthenticatedUsersIdEditRoute: typeof AuthenticatedUsersIdEditRoute
  AuthenticatedUsersIdViewRoute: typeof AuthenticatedUsersIdViewRoute
}

const AuthenticatedUsersIdRouteChildren: AuthenticatedUsersIdRouteChildren = {
  AuthenticatedUsersIdEditRoute: AuthenticatedUsersIdEditRoute,
  AuthenticatedUsersIdViewRoute: AuthenticatedUsersIdViewRoute,
}

const AuthenticatedUsersIdRouteWithChildren =
  AuthenticatedUsersIdRoute._addFileChildren(AuthenticatedUsersIdRouteChildren)

interface AuthenticatedUsersRouteChildren {
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRouteWithChildren
  AuthenticatedUsersCreateRoute: typeof AuthenticatedUsersCreateRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedUsersRouteChildren: AuthenticatedUsersRouteChildren = {
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRouteWithChildren,
  AuthenticatedUsersCreateRoute: AuthenticatedUsersCreateRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedUsersRouteWithChildren =
  AuthenticatedUsersRoute._addFileChildren(AuthenticatedUsersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppsRoute: typeof AuthenticatedAppsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppsRoute: AuthenticatedAppsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
